export const citiesByCountry = {
  'NE': [
    { id: 'niamey', name: 'Niamey', region: 'Niamey' },
    { id: 'zinder', name: 'Zinder', region: 'Zinder' },
    { id: 'maradi', name: 'Maradi', region: 'Maradi' },
    { id: 'tahoua', name: 'Tahoua', region: 'Tahoua' },
    { id: 'agadez', name: 'Agadez', region: 'Agadez' },
    { id: 'dosso', name: 'Dosso', region: 'Dosso' },
    { id: 'diffa', name: 'Diffa', region: 'Diffa' },
    { id: 'tillaberi', name: 'Tillabéri', region: 'Tillabéri' },
  ],
  'SN': [
    { id: 'dakar', name: 'Dakar', region: 'Dakar' },
    { id: 'thies', name: 'Thiès', region: 'Thiès' },
    { id: 'kaolack', name: 'Kaolack', region: 'Kaolack' },
    { id: 'saint_louis', name: 'Saint-Louis', region: 'Saint-Louis' },
    { id: 'ziguinchor', name: 'Ziguinchor', region: 'Ziguinchor' },
    { id: 'diourbel', name: 'Diourbel', region: 'Diourbel' },
    { id: 'louga', name: 'Louga', region: 'Louga' },
    { id: 'tambacounda', name: 'Tambacounda', region: 'Tambacounda' },
  ],
  'ML': [
    { id: 'bamako', name: 'Bamako', region: 'Bamako' },
    { id: 'sikasso', name: 'Sikasso', region: 'Sikasso' },
    { id: 'mopti', name: 'Mopti', region: 'Mopti' },
    { id: 'segou', name: 'Ségou', region: 'Ségou' },
    { id: 'kayes', name: 'Kayes', region: 'Kayes' },
    { id: 'koulikoro', name: 'Koulikoro', region: 'Koulikoro' },
    { id: 'gao', name: 'Gao', region: 'Gao' },
    { id: 'tombouctou', name: 'Tombouctou', region: 'Tombouctou' },
  ],
  'BF': [
    { id: 'ouagadougou', name: 'Ouagadougou', region: 'Centre' },
    { id: 'bobo_dioulasso', name: 'Bobo-Dioulasso', region: 'Hauts-Bassins' },
    { id: 'koudougou', name: 'Koudougou', region: 'Centre-Ouest' },
    { id: 'ouahigouya', name: 'Ouahigouya', region: 'Nord' },
    { id: 'banfora', name: 'Banfora', region: 'Cascades' },
    { id: 'kaya', name: 'Kaya', region: 'Centre-Nord' },
    { id: 'tenkodogo', name: 'Tenkodogo', region: 'Centre-Est' },
    { id: 'fada_ngourma', name: 'Fada N\'Gourma', region: 'Est' },
  ],
  'CI': [
    { id: 'abidjan', name: 'Abidjan', region: 'Lagunes' },
    { id: 'yamoussoukro', name: 'Yamoussoukro', region: 'Lacs' },
    { id: 'bouake', name: 'Bouaké', region: 'Vallée du Bandama' },
    { id: 'daloa', name: 'Daloa', region: 'Haut-Sassandra' },
    { id: 'san_pedro', name: 'San-Pédro', region: 'Bas-Sassandra' },
    { id: 'korhogo', name: 'Korhogo', region: 'Savanes' },
    { id: 'man', name: 'Man', region: 'Montagnes' },
    { id: 'divo', name: 'Divo', region: 'Sud-Bandama' },
  ],
  'GH': [
    { id: 'accra', name: 'Accra', region: 'Greater Accra' },
    { id: 'kumasi', name: 'Kumasi', region: 'Ashanti' },
    { id: 'tamale', name: 'Tamale', region: 'Northern' },
    { id: 'cape_coast', name: 'Cape Coast', region: 'Central' },
    { id: 'sekondi_takoradi', name: 'Sekondi-Takoradi', region: 'Western' },
    { id: 'ho', name: 'Ho', region: 'Volta' },
    { id: 'koforidua', name: 'Koforidua', region: 'Eastern' },
    { id: 'sunyani', name: 'Sunyani', region: 'Brong-Ahafo' },
  ],
  'NG': [
    { id: 'lagos', name: 'Lagos', region: 'Lagos' },
    { id: 'abuja', name: 'Abuja', region: 'FCT' },
    { id: 'kano', name: 'Kano', region: 'Kano' },
    { id: 'ibadan', name: 'Ibadan', region: 'Oyo' },
    { id: 'port_harcourt', name: 'Port Harcourt', region: 'Rivers' },
    { id: 'benin_city', name: 'Benin City', region: 'Edo' },
    { id: 'maiduguri', name: 'Maiduguri', region: 'Borno' },
    { id: 'zaria', name: 'Zaria', region: 'Kaduna' },
  ],
};

export const getCitiesByCountry = (countryCode) => {
  return citiesByCountry[countryCode] || [];
};