export const mockBeneficiaries = [
  {
    id: '1',
    name: 'Fatima Oumarou',
    phone: '+227 90 12 34 56',
    location: 'Niamey, Niger',
    service: 'mynita',
  },
  {
    id: '2',
    name: 'Ibrahim Mounkaila',
    phone: '+227 96 78 90 12',
    location: 'Zinder, Niger',
    service: 'amana',
  },
  {
    id: '3',
    name: 'Aisha Abdoulaye',
    phone: '+227 94 56 78 90',
    location: 'Maradi, Niger',
    service: 'mynita',
  },
  {
    id: '4',
    name: 'Moussa Garba',
    phone: '+227 92 34 56 78',
    location: 'Tahoua, Niger',
    service: 'amana',
  },
];

export const mockTransactions = [
  {
    id: 'TXN001',
    recipient: 'Fatima Oumarou',
    amount: 150.00,
    fees: 3.75,
    receivedAmount: 98400,
    service: 'MyNITA',
    status: 'completed',
    date: '15 Jan 2024',
    time: '14:30',
    reference: 'MTN240115001',
  },
  {
    id: 'TXN002',
    recipient: 'Ibrahim Mounkaila',
    amount: 200.00,
    fees: 3.60,
    receivedAmount: 130800,
    service: 'Amana-ta',
    status: 'completed',
    date: '12 Jan 2024',
    time: '10:15',
    reference: 'AMN240112001',
  },
  {
    id: 'TXN003',
    recipient: 'Aisha Abdoulaye',
    amount: 100.00,
    fees: 2.50,
    receivedAmount: 65600,
    service: 'MyNITA',
    status: 'pending',
    date: '14 Jan 2024',
    time: '16:45',
    reference: 'MTN240114001',
  },
  {
    id: 'TXN004',
    recipient: 'Moussa Garba',
    amount: 300.00,
    fees: 5.40,
    receivedAmount: 196200,
    service: 'Amana-ta',
    status: 'completed',
    date: '10 Jan 2024',
    time: '09:30',
    reference: 'AMN240110001',
  },
  {
    id: 'TXN005',
    recipient: 'Fatima Oumarou',
    amount: 250.00,
    fees: 6.25,
    receivedAmount: 164000,
    service: 'MyNITA',
    status: 'failed',
    date: '08 Jan 2024',
    time: '11:20',
    reference: 'MTN240108001',
  },
  {
    id: 'TXN006',
    recipient: 'Ibrahim Mounkaila',
    amount: 120.00,
    fees: 2.16,
    receivedAmount: 78480,
    service: 'Amana-ta',
    status: 'completed',
    date: '06 Jan 2024',
    time: '15:00',
    reference: 'AMN240106001',
  },
  {
    id: 'TXN007',
    recipient: 'Aisha Abdoulaye',
    amount: 180.00,
    fees: 4.50,
    receivedAmount: 118080,
    service: 'MyNITA',
    status: 'completed',
    date: '05 Jan 2024',
    time: '13:45',
    reference: 'MTN240105001',
  },
  {
    id: 'TXN008',
    recipient: 'Moussa Garba',
    amount: 80.00,
    fees: 1.44,
    receivedAmount: 52320,
    service: 'Amana-ta',
    status: 'pending',
    date: '13 Jan 2024',
    time: '17:30',
    reference: 'AMN240113001',
  },
];

export const mockFAQs = [
  {
    id: '1',
    question: 'Combien de temps prend un transfert ?',
    answer: 'Les transferts via MyNITA prennent généralement 1-3 minutes, tandis que les transferts via Amana-ta peuvent prendre 5-10 minutes.',
    category: 'Transferts',
  },
  {
    id: '2',
    question: 'Quels sont les frais de transfert ?',
    answer: 'Les frais varient selon le service choisi : MyNITA facture 2.5% et Amana-ta facture 1.8% du montant envoyé.',
    category: 'Frais',
  },
  {
    id: '3',
    question: 'Quel est le montant minimum et maximum ?',
    answer: 'Le montant minimum est de 10€ et le maximum est de 1000€ par transaction. La limite mensuelle est de 5000€.',
    category: 'Limites',
  },
  {
    id: '4',
    question: 'Comment puis-je suivre mon transfert ?',
    answer: 'Vous pouvez suivre votre transfert dans la section "Historique" de l\'application avec le numéro de référence fourni.',
    category: 'Suivi',
  },
  {
    id: '5',
    question: 'Que faire si mon transfert échoue ?',
    answer: 'Si votre transfert échoue, l\'argent sera automatiquement remboursé sur votre compte dans les 24-48 heures. Contactez le support si nécessaire.',
    category: 'Problèmes',
  },
  {
    id: '6',
    question: 'Comment vérifier mon compte ?',
    answer: 'Pour vérifier votre compte, téléchargez une pièce d\'identité valide et prenez un selfie dans la section "Profil" de l\'application.',
    category: 'Vérification',
  },
];